### ISSUE TITLE
Nommage des fichiers

### ISSUE THREAD

**Issue by cedricmarie** [fser/aide-lautrenet#14]
Juste une proposition : Plutôt que d'utiliser un tableau de correspondance entre les rubriques et les noms de fichiers, est-ce qu'on ne pourrait pas plus simplement renommer les fichiers avec des noms plus explicites, en utilisant l'index comme préfixe pour faire en sorte que l'ordre alphabétique les liste dans l'ordre.
Par exemple : #rub.titre-rubrique.#art.titre-article.md
Ce qui donnerait :
01.bienvenue.01.bienvenue-a-lautre-net.md
02.interface.01.connexion.md
02.interface.02.prise-en-mains.md
etc...
Ainsi on s'y retrouverait plus facilement, et l'insertion d'un nouvel article le ferait apparaître automatiquement au bon endroit dans l'arborescence.
Je pose la question maintenant, car git ne gérant pas l'historique d'un fichier quand il est renommé, il est préférable de faire ce changement le plus tôt possible, si on décide de le faire.
(NB : Et si c'est le cas, je me propose de faire le boulot... en fournissant un script de "git mv" par exemple, car un patch ne serait pas très adapté à ce genre de modification...)

**Comment by cedricmarie** [comment]
Ou plus simple : des sous-répertoires 01.bienvenue, 02.interface, et à l'intérieur des fichiers 01.bienvenue-a-lautre-net.md, 01.connexion.md, ...
Pelican a l'air de le supporter, il regarde dans tous les sous-répertoires.

**Comment by fser** [comment]
J'avoue ne pas avoir essayé de renommer les fichiers. Pourquoi pas!

**Comment by cedricmarie** [comment]
Mon script en pièce jointe (à renommer en .sh...).
J'ai renommé bêtement, certains articles n'ont pas de numéro, certains ont deux fois le même numéro (dans les listes de discussion), je n'ai pas cherché à modifier quoi que ce soit : c'est juste équivalent, organisé différemment.
[git-mv.txt](https://github.com/fser/aide-lautrenet/files/1738286/git-mv.txt)

**Comment by fser** [comment]
allé on essaye. Si demain aide.lautre.net est cassé, on rollbackera ;)

**Comment by cedricmarie** [comment]
Ça m'a l'air d'être passé... Merci de l'avoir appliqué aussi rapidement :)
